export const selectionOptions = {
  PROGRAMMES: [
    { text: 'Aerospace Engineering', value: 'aerospace' },
    { text: 'Agricultural and Biosystems Engineering', value: 'agric' },
    { text: 'Automobile Engineering', value: 'automobile' },
    { text: 'Geomatic Engineering', value: 'geomatic' },
    { text: 'Biomedical Engineering', value: 'biomed' },
    { text: 'Chemical Engineering', value: 'chemical' },
    { text: 'Civil Engineering', value: 'civil' },
    { text: 'Computer Engineering', value: 'die' },
    { text: 'Electrical/Electronic Eng', value: 'electrical' },
    { text: 'Geological Engineering', value: 'geological' },
    { text: 'Industrial Engineering', value: 'industrial' },
    { text: 'Materials Engineering', value: 'materials' },
    { text: 'Marine Engineering', value: 'marine' },
    { text: 'Metallurgical Engineering', value: 'matallurgical' },
    { text: 'Petroleum Engineering', value: 'petroleum' },
    { text: 'Petrochemical Engineering', value: 'petrochemical' },
    { text: 'Telecommunications Engineering', value: 'telecom' },
  ],
  DEPARTMENTS: [
    { text: 'Agricultural Engineering Department', value: 'agricDept' },
    { text: 'Chemical Engineering Department', value: 'chemicalDept' },
    { text: 'Civil Engineering Department', value: 'civilDept' },
    { text: 'Computer Engineering Department', value: 'computerDept' },
    {
      text: 'Electrical/Electronic Engineering Department',
      value: 'electricalDept',
    },
    { text: 'Geological Engineering Department', value: 'geologicalDept' },
    { text: 'Materials Engineering Department', value: 'materialsDept' },
    { text: 'Mechanical Engineering Department', value: 'mechanicalDept' },
    { text: 'Petroleum Engineering Department', value: 'petroleumDept' },
  ],
  YESORNO: [
    { text: 'Yes', value: 1 },
    { text: 'No', value: 0 },
  ],
};
